[tools]
selene = { source = "Kampfkarren/selene", version = "0.19.1" }
stylua = { source = "JohnnyMorganz/stylua", version = "0.14.0" }
rojo = { source = "rojo-rbx/rojo", version = "7.2.1" }
# run-in-roblox = { source = "rojo-rbx/run-in-roblox", version = "0.3.0" }
