[package]
name = "ok-nick/layoututil"
version = "3.0.0-rc.1"
description = "A library for dynamically sized `ScrollingFrames` with dynamically sized elements, without stretching."
authors = ["ok-nick <nick.libraries@gmail.com>"]
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
include = [
  "src",
  "default.project.json",
  "LICENSE",
  "README.md",
  "wally.toml",
  "wally.lock",
]
exclude = ["**"]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
