name: deploy 
on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install tooling
      uses: ok-nick/setup-aftman@v0
      with:
        trust-check: false

    - name: Build files
      run: |
        rojo build --output bin/LayoutUtil.rbxm
        rojo build bin/plugin.project.json --output bin/LayoutUtil-Plugin.rbxm

    # TODO: upload to wally and npm
    # - name: Upload
    #   run: |
    #     rojo upload bin/library.project.json --asset_id 6723754061 --cookie ${{ secrets.ROBLOSECURITY }}
    #     rojo upload bin/plugin.project.json --asset_id 6723751472 --cookie ${{ secrets.ROBLOSECURITY }}

    - name: Download ripgrep
      run: gh release download --repo BurntSushi/ripgrep --pattern *x86_64-unknown-linux-musl.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Install ripgrep
      run: |
        mkdir ripgrep
        tar -xvzf ripgrep*.tar.gz -C ripgrep --strip-components=1
        echo "$GITHUB_WORKSPACE/ripgrep" >> $GITHUB_PATH

    - name: Get version
      run: |
        VERSION=`rg 'version = "([^"]+)' wally.toml --replace '$1' --only-matching`
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Get description
      run: |
        DESCRIPTION=`rg '###\s(.(?!##\s|\[Unreleased\]))+' CHANGELOG.md --pcre2 --multiline --multiline-dotall --max-count 1 --no-filename --no-line-number`
        echo "DESCRIPTION<<EOF" >> $GITHUB_ENV
        echo "$DESCRIPTION" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: v${{ env.VERSION }}
        tag_name: v${{ env.VERSION }}
        body: ${{ env.DESCRIPTION }}
        files: |
          bin/LayoutUtil.rbxm
          bin/LayoutUtil-Plugin.rbxm
      env:
        GITHUB_TOKEN: ${{ github.token }}
